//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int ORDERID { get; set; }
        public Nullable<int> PURCHASEAMT { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<int> RESULT { get; set; }
        public string RESULTDESC { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string RRN { get; set; }
        public string DEALID { get; set; }
        public string USERID { get; set; }
    }
}
