//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GroupResult
    {
        public string dt { get; set; }
        public string UserName { get; set; }
        public Nullable<int> sum1 { get; set; }
        public Nullable<int> sum2 { get; set; }
        public Nullable<int> sum3 { get; set; }
    }
}
